# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-scopes}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Myles Byrne"]
  s.date = %q{2009-11-04}
  s.email = %q{myles@myles.id.au}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "example_app.rb",
     "examples.rb",
     "lib/sinatra/scopes.rb",
     "sinatra-scopes.gemspec"
  ]
  s.homepage = %q{http://github.com/quackingduck/sinatra-scopes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple request handler scoping for sinatra}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_development_dependency(%q<exemplor>, [">= 2000.0.0"])
      s.add_development_dependency(%q<rack-test>, ["= 0.4.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_dependency(%q<exemplor>, [">= 2000.0.0"])
      s.add_dependency(%q<rack-test>, ["= 0.4.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    s.add_dependency(%q<exemplor>, [">= 2000.0.0"])
    s.add_dependency(%q<rack-test>, ["= 0.4.0"])
  end
end
